name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-deno:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Fmt Lint Deno Module
        run: deno fmt --check
      - name: Lint Deno Module
        run: deno lint
      - name: Check Deno Module
        run: deno check lib.ts

  test-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Cargo Fmt
        run: cargo fmt -- --check

      # Default features
      - name: Cargo Clippy Default Features
        run: cargo clippy -- -D warnings
      - name: Cargo Test Default Features
        run: cargo test

      # All features
      - name: Cargo Clippy All Features
        run: cargo clippy --all-features -- -D warnings
      - name: Cargo Test All Features
        run: cargo test --all-features

  test-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Shellcheck
        run: |
          for file in $(find . -type f -name "*.sh"); do
            echo "Running shellcheck on $file"
            shellcheck "$file"
          done

  cargo-deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deny
        uses: EmbarkStudios/cargo-deny-action@v1

  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2

    - name: Check spelling
      uses: crate-ci/typos@master
